//  I AM LEARNING GIT AND GITHUB. I'M GOING TO MAKE SOME CHANGES TO SEE HOW GIT TRACKS MY EDITS AND I WILL COMMIT THIS

//AGAIN I AM WRITING SOMETHING TO COMMIT AGAIN

//GIT STEPS
//FIRST, WE HAVE TO INITIALIZE GIT SO THAT IT KNOWS THE PROJECT IS READY TO BE TRACKED.
