//  I AM LEARNING GIT AND GITHUB. I'M GOING TO MAKE SOME CHANGES TO SEE HOW GIT TRACKS MY EDITS AND I WILL COMMIT THIS

//AGAIN I AM WRITING SOMETHING TO COMMIT AGAIN

//GIT STEPS
//FIRST, WE HAVE TO INITIALIZE GIT SO THAT IT KNOWS THE PROJECT IS READY TO BE TRACKED.
//SECOND, WE HAVE TO ADD (STAGE) THE FILE, WHICH MEANS GIT NOW KNOWS THIS FILE IS BEING TRACKED AND WILL MONITOR ANY CHANGES MADE TO IT.
//THIRD STEP WILL COMMIT THIS MEAN GIT WILL TAKE SCREENSHOT
//NOW I AM LEARNING ABOUT BRANCHING IN GIT AND
//I CREATED A NEW BRANCH CALLED FEATURE/LEARNING
//IN THIS BRANCH ALSO I AM WRITING SOMETHING
//TO TEST WHAT IS GIT CONFLICT
